{{- if .Values.config.typha.enabled }}
---
apiVersion: {{ include "deploymentversion" . }}
kind: Deployment
metadata:
  name: calico-typha-horizontal-autoscaler
  namespace: kube-system
  labels:
    k8s-app: calico-typha-autoscaler
spec:
  revisionHistoryLimit: 5
  replicas: 1
  selector:
    matchLabels:
      k8s-app: calico-typha-autoscaler
  template:
    metadata:
      annotations:
        checksum/configmap-calico-typha-horizontal-autoscaler: {{ include (print $.Template.BasePath "/typha-cpha/configmap-typha-horizontal-autoscaling.yaml") . | sha256sum }}
      labels:
        networking.gardener.cloud/to-public-networks: allowed
        networking.gardener.cloud/to-apiserver: allowed
        networking.gardener.cloud/to-dns: allowed
        origin: gardener
        k8s-app: calico-typha-autoscaler
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      priorityClassName: system-cluster-critical
      # Make sure to not use the coredns for DNS resolution.
      dnsPolicy: Default
      securityContext:
        supplementalGroups: [ 65532 ]
        fsGroup: 65532
        runAsUser: 65532
      containers:
        - image: {{ index .Values.images "calico-cpa" }}
          name: autoscaler
          command:
            - /cluster-proportional-autoscaler
            - --namespace=kube-system
            - --configmap=calico-typha-horizontal-autoscaler
            - --target=deployment/calico-typha-deploy
            - --logtostderr=true
            - --v=2
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              memory: 100Mi
      serviceAccountName: typha-cpha
{{- end }}
