{{- if .Values.config.typha.enabled }}
---
apiVersion: {{ include "deploymentversion" . }}
kind: Deployment
metadata:
  name: calico-typha-vertical-autoscaler
  namespace: kube-system
  labels:
    k8s-app: calico-typha-autoscaler
spec:
  revisionHistoryLimit: 5
  replicas: 1
  selector:
    matchLabels:
      k8s-app: calico-typha-autoscaler
  template:
    metadata:
      annotations:
        checksum/configmap-calico-typha-vertical-autoscaler: {{ include (print $.Template.BasePath "/typha-cpva/configmap-typha-vertical-autoscaling.yaml") . | sha256sum }}
      labels:
        networking.gardener.cloud/to-public-networks: allowed
        networking.gardener.cloud/to-apiserver: allowed
        networking.gardener.cloud/to-dns: allowed
        origin: gardener
        k8s-app: calico-typha-autoscaler
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      priorityClassName: system-cluster-critical
      # Make sure to not use the coredns for DNS resolution.
      dnsPolicy: Default
      securityContext:
        runAsUser: 65534
      containers:
        - image:  {{ index .Values.images "calico-cpva" }}
          name: autoscaler
          command:
            - /cpvpa
            - --target=deployment/calico-typha-deploy
            - --namespace=kube-system
            - --logtostderr=true
            - --poll-period-seconds=30
            - --v=2
            - --config-file=/etc/config/typha-autoscaler
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              memory: 130Mi
          volumeMounts:
            - name: config
              mountPath: /etc/config
      volumes:
        - name: config
          configMap:
            name: calico-typha-vertical-autoscaler
      serviceAccountName: typha-cpva
{{- end }}
